import request from "graphql-request";
import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import Link from "next/link";
import { graphql } from "@/gql";
import { env } from "@/env";

const GET_USERS = graphql(`
  query GetUsers {
    userCollection {
      edges {
        node {
          id
        }
      }
    }
  }
`);

export default function Home() {
  const { data, error, isLoading } = useQuery({
    queryKey: ["ministry"],
    queryFn: async () => request(env.NEXT_PUBLIC_GRAPHQL_SCHEMA, GET_USERS),
  });
  // console.log(data);
  if (isLoading) return <p>Loading...</p>;
  if (error) return <p>Error: {error.message}</p>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {data?.userCollection?.edges.map((d) => (
              <Link
                key={d.node.id}
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="https://create.t3.gg/"
                target="_blank"
              >
                <h3 className="text-2xl font-bold">{d.node.id}</h3>
                <div className="text-lg">{d.node.__typename}</div>
              </Link>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
